### ISSUE TITLE
Add -> CRAFT: Create React App From Template

### ISSUE THREAD

**Issue by timarney** [tuchk4/awesome-create-react-app#5]
Not sure where this would fit in your repo but I think it's worth adding:

https://medium.com/@stoyanstefanov/craft-create-react-app-from-template-7fd3383d0954#.m341rutmt

**Comment by tuchk4** [comment]
@timarney Thanks!

I think `Tools` section will be very fine


btw. Already pushed to master.

Also while I was playing with CRAFT I've created [CRA template with Redux and Router](https://github.com/tuchk4/craft-redux)
